apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-all
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sunaofficial/ecommerce-gitops.git
    targetRevision: main
    path: frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
